name: Matrix workflow 
on:
    push 
jobs:
    build:
        strategy:
            matrix:
                node-version: [12, 14, 16]
                os-key: [ubuntu-latest, windows-latest]
                exclude:
                    - node-version: 12
                      os-key: ubuntu-latest
                      os-key: windows-latest
        continue-on-error: true
        runs-on: ${{ matrix.os-key }}
        steps:
            - name: Git Code 
              uses: actions/checkout@v6
            - name: Install Node
              uses: actions/setup-node@v6
              with:
                node-version: ${{ matrix.node-version}}
            - name: install Depn
              run: npm ci
            - name: build project
              run: npm run build
