name : Reusable Workflow
on:
    workflow_call:
        inputs:
            artifact-name: 
                default: dist
                description: This is the downloded artifact
                required: true 
                type: string
        outputs:
            result:
                description: "result of output or deploy job"
                value: ${{ jobs.deploy.outputs.new-result }}
jobs:
    deploy:
        outputs:
            new-result: ${{ steps.id_output.outputs.result}}
        runs-on: ubuntu-latest
        steps:
            - name: Download-Artifact
              uses: actions/download-artifact@v7
              with:
                name: ${{ inputs.artifact-name }}
            - name: Output Information
              run: |
                echo "Deploy && Upload .."
                echo "show Deploy ..."
            - name: Emit Output
              id: id_output
              run: echo "result=SUCCESS" >> ${GITHUB_OUTPUT}
    